name: Unlighthouse Audit Report

on:
  workflow_dispatch:
    inputs:
      site_url:
        description: 'URL to audit'
        required: true
        default: 'https://site-scrape.vercel.app/'

jobs:
  unlighthouse-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Unlighthouse
        run: npm install -g @unlighthouse/cli puppeteer

      - name: Run Unlighthouse Audit
        run: unlighthouse-ci --site ${{ github.event.inputs.site_url }} --reporter jsonExpanded --budget 75 --build-static

      - name: Upload Unlighthouse Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: unlighthouse-report
          path: ./
